yuminn-k/project_JITSU-deployment-repo

.gitignore, src/Router.tsx, src/components/layout/googleLoginButton/index.tsx, src/pages/index.tsx, src/pages/login.tsx
- `구글 소셜 로그인` 로직 구현
##
- 레이아웃은 추후 작업 예정
=> ✨ feat : Implement Google social login logic

src/index.tsx, src/pages/login.tsx
- `로그인 페이지` 레이아웃 구현 완료
- `로고` 추가 요함
=> 💄 style : Implement Login page layout

app/Http/Controllers/WordController.php, package-lock.json, resources/css/app.css, resources/views/components/card.blade.php, resources/views/dashboard.blade.php, routes/web.php
* カードコンポーネントにデータを出力し、アニメーションを追加
* `WordController`に`index`メソッドを追加し、`Cardコンポーネント`のアニメーションとデータ出力を追加
* なし
* なし
* なし …
=> カードコンポーネントにデータを出力し、アニメーションを追加する

app/Http/Controllers/WordController.php, app/Models/Word.php, resources/views/dashboard.blade.php, routes/web.php
* ダッシュボード表示にランダムワード機能を追加
* `Cardコンポーネント`のランダム抽出ロジック実装
* なし
* なし
* なし
---
=> ✨ feat: Add random word functionality to dashboard view

database/migrations/2023_11_04_090232_create_user_words_table.php
* `userwords`テーブル名を`user_words`に変更
* マイグレーションファイルとテーブル名が変更
* なし
* なし
* なし
---
=> 🚚 refactor: Rename migration file userwords to user_words table

resources/views/layouts/navigation.blade.php
* ナビゲーションバー名変更
* ナビゲーションバー名を`掲示板`から`コミュニティ`に変更
* なし
* なし
* 
#
---
=> ♻️ refactor: Update translations and add user word status update functionality

app/Http/Controllers/UserWordController.php, app/Models/UserWord.php, database/migrations/2023_11_04_090232_create_user_words_table.php, resources/views/components/card.blade.php, routes/web.php
* `UserWord`管理ロジックを実装
* UserWord`管理のためにお気に入り、知らない単語追加ロジックを実装
* なし
* なし
*
#
---
=> ✨ feat: Add UserWord logic

package-lock.json, package.json, resources/views/components/profile-card.blade.php, resources/views/profile/partials/delete-user-form.blade.php, resources/views/profile/partials/update-password-form.blade.php, resources/views/profile/partials/update-profile-information-form.blade.php, resources/views/profile/profile.blade.php
* `Profile`ページレイアウトの実装
* `プロフィール情報変更`、`パスワード変更`、`アカウント削除`機能を**モーダル**で実装
* `profile-card.blade.php`コンポーネントを実装して`resources/views/profile/profile.blade.php`に適用
* なし
* なし
*  なし
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 …
=> ✨ feat: Update dependencies and add profile view and forms

resources/views/dashboard.blade.php
* インデントルールに合わせて改善
* `resources/views/dashboard.blade.php`の`script`の部分をインデントルールに合わせて改善
* なし
* なし
* なし
#
---
=> ✨ feat: Refactor DOMContentLoaded event listener and add fetch error handling

resources/views/layouts/navigation.blade.php, resources/views/main.blade.php
* `ヘッダー`レイアウトの統一
* `メインページ`での`ヘッダー`を変更
* なし
* なし
* なし
#
---
=> 💄 style: Update header include in main view

app/Http/Controllers/ProfileController.php, app/Http/Controllers/UserWordController.php, app/Models/User.php, app/Models/UserWord.php, app/Models/Word.php, resources/views/components/profile-card.blade.php, resources/views/profile/partials/favorite-word-form.blade.php, resources/views/profile/partials/tag-setting-form.blade.php, resources/views/profile/partials/unfamiliar-word-form.blade.php
* `お気に入り`, `知らない`ページのモーダルページの実装
* `タッグ設定`ページは実装中
* `Profile`ページに`お気に入り`, `知らない`, `タッグ設定`機能のモーダルボタンとページを実装
* なし
* なし
*なし
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …
=> ✨ feat: Implement Profile page modal

app/Http/Controllers/WordController.php, resources/views/components/card.blade.php, resources/views/dashboard.blade.php
* `Card`コンポーネントのリファクタリングと次の単語情報を取得する機能を実装
* `Card`コンポーネントの内部にあったボタンを外部に出して、ランダムに別の単語を取得するロジックを実装
* なし
* なし
* なし
# …
=> ✨ feat: Add random word display to dashboard

resources/views/profile/partials/delete-user-form.blade.php, resources/views/profile/partials/favorite-word-form.blade.php, resources/views/profile/partials/tag-setting-form.blade.php, resources/views/profile/partials/unfamiliar-word-form.blade.php, resources/views/profile/partials/update-password-form.blade.php, resources/views/profile/partials/update-profile-information-form.blade.php
* `Closeボタン`を押すとモーダルレイアウトが異常に変わるエラーの修正
* `closeModal`の呼び出し方法を変更
* なし
* なし
* なし
#
---
=> 🐛 fix: Fix modal close button in profile partials forms

app/Http/Controllers/UserTagController.php, app/Models/Tag.php, app/Models/User.php, app/Models/UserTag.php, database/migrations/2023_11_04_095318_create_user_tags_table.php, resources/views/profile/partials/tag-setting-form.blade.php, routes/web.php
migrations
* `user`ごとに好きな用語を学習できるように`tag`のカスタム化
* `userTag`関連ロジックを追加
* なし
* なし
* なし
#
---
=> ✨ feat: Add UserTagController and related models and

resources/views/components/profile-card.blade.php, resources/views/profile/partials/delete-user-form.blade.php, resources/views/profile/partials/favorite-word-form.blade.php, resources/views/profile/partials/tag-setting-form.blade.php, resources/views/profile/partials/unfamiliar-word-form.blade.php, resources/views/profile/partials/update-password-form.blade.php, resources/views/profile/partials/update-profile-information-form.blade.php
* マイページの`レイアウトの変更`
* マイページの全般的なUIを改善
* なし
* なし
* なし
#
---
=> 💄 style: Add tag setting modal to profile card component

resources/views/components/main-body.blade.php
main-body component
* メインページの数字を削除
* メインページのUIの変化
* なし
* なし
* なし
#
---
=> 💄 style: Update Japanese IT terms and fix typos in

Procfile
* `cloudtype`で配布するための設定ファイル追加
* ルートディレクトリに`Procfile`ファイルを追加
* なし
* なし
* なし
#
---
=> 🚀 deploy: Add Procfile for Heroku deployment

package-lock.json, package.json
* `package.json`の更新
* tailwindcssの追加
* なし
* なし
* なし
#
---
=> 💚 build: Update @tailwindcss/forms to version 0.5.7

public/.htaccess
* HTTPS関係のエラーを解決するため
* `.htaccess`ファイルに設定を追加
* なし
* なし
* なし
#
---
=> 🚀 deploy: Add HTTPS redirect to .htaccess file

public/.htaccess
* Redirectionエラーの解決
* HTTPSに強制するコードを削除
* なし
* なし
* なし
#
---
=> 🚑 fix: Remove HTTPS redirect from .htaccess file

resources/views/profile/partials/favorite-word-form.blade.php, resources/views/profile/partials/unfamiliar-word-form.blade.php
word forms
* アニメーションが正常に動作しないバグを解決
* window.onload関連のロジックを再実装
* なし
* なし
* なし
#
---
=> 🐛 fix: Fix card flip animation in favorite and unfamiliar

resources/views/layouts/app.blade.php, resources/views/layouts/guest.blade.php
* 不要なlinkコードを削除
* 不要なlinkコードを削除
* なし
* なし
* なし
#
---
=> ♻️ refactor: Comment out link to app.css in layout files

resources/views/layouts/app.blade.php, resources/views/layouts/guest.blade.php
* cssが適用されないバグ修正
* linkコードを追加
* なし
* なし
* なし
#
---
=> 🐛 fix: Update asset paths in app and guest layouts.

resources/views/layouts/app.blade.php, resources/views/layouts/guest.blade.php
* cssが適用されないバグ修正
* cssが適用されないバグ修正
* cssが適用されないバグ修正
* なし
* なし
#
---
=> 🐛 fix: Update asset paths in app and guest layouts

app/Http/Controllers/Auth/RegisteredUserController.php, app/Models/User.php
* 会員登録後、基本情報登録ロジックを追加
* Tag, UserTag 関連ロジックを追加
* なし
* なし
* なし
#
---
=> ✨ feat: Add UserTag model and create tag for new user

app/Http/Controllers/UserWordController.php
* 読みやすいメソッドに名前を変更
* `update`メソッドを`addWordPad`に変更
* なし
* なし
* なし
#
---
=> ♻️ refactor: Change method name from update to addWordPad

resources/views/profile/partials/delete-user-form.blade.php, resources/views/profile/partials/tag-setting-form.blade.php, resources/views/profile/partials/update-password-form.blade.php, resources/views/profile/partials/update-profile-information-form.blade.php
* ボタンクリック時のユーザーエクスペリエンスの改善
* ボタンクリック時の効果追加
* なし
* なし
* なし
#
---
=> 💄 style: Add button scaling on click in profile forms

resources/views/components/card.blade.php, resources/views/dashboard.blade.php, resources/views/profile/partials/favorite-word-form.blade.php, resources/views/profile/partials/unfamiliar-word-form.blade.php
* カードの背景の状態で次のカードに移動したとき、前景ではなく背景の状態で移動するロジックを改善しました。
* 次のカードに移動する際、背景の状態であれば、前景に移動するロジックを追加。
* なし
* なし
* なし
#
---
=> 💄 style: Add styles and functionality to card and buttons

resources/views/board.blade.php
* `Board`基礎レイアウトの生成
* `Board`ページの基本レイアウト作成
* なし
* なし
* なし
#
---
=> 💄 style: Add community board view with messages

routes/web.php
* `WordController`の`store`メソッドルートの追加
* `web.php`ファイルに`WordController`の`store`メソッドルートの追加
* なし
* なし
* なし
#
---
=> ✨ feat: Add word storage and word status endpoint

database/factories/WordFactory.php, tests/Feature/WordControllerTest.php
* テストコードを追加
* `WordController`の`store`メソッドのテストコード追加
* `WordFactory`コードを追加
* テストコードに変なところや改善点があるか
* なし
#
---
=> ✅ test: Add WordFactory and WordControllerTest

crawl.py
functionality
* タグごとに収集されないクロールロジックを修正
* URL指定ロジックを変更
* なし
* なし
* なし
#
---
=> ♻️ refactor: Refactor code to improve efficiency and add new

app/Http/Controllers/Auth/RegisteredUserController.php, app/Http/Controllers/UserWordController.php, app/Models/UserTag.php, app/Models/UserWord.php, resources/views/dashboard.blade.php, resources/views/profile/partials/favorite-word-form.blade.php, resources/views/profile/partials/unfamiliar-word-form.blade.php
* `words` テーブルのカラム名を変更する際に発生したエラーの修正
* `words_number`で発生したエラーを`id`に変更
* なし
* なし
* なし
#
---
=> 🚑 fix: Fix model relationships and update word IDs

resources/views/layouts/navigation.blade.php
* コミュニティページでナビゲーションバーが正常に出力されないエラーを解決
* ナビゲーションバーにあった`hidden`属性を削除
* なし
* なし
* なし
#
---
=> 💄 style: Update navigation layout

app/Http/Controllers/CommentController.php, app/Http/Controllers/PostController.php, app/Models/Comment.php, app/Models/Post.php, app/Policies/CommentPolicy.php, app/Providers/AuthServiceProvider.php, database/migrations/2023_11_04_095242_create_comments_table.php, resources/views/board.blade.php, routes/web.php
* コミュニティページのレイアウトとロジックを実装
* コミュニティページの実装に必要なロジックとレイアウトの実装完了
* なし
* なし
* なし
#
---
=> Implement Community page

app/Http/Controllers/CommentController.php, app/Http/Controllers/PostController.php, app/Http/Controllers/ProfileController.php, app/Http/Controllers/UserTagController.php, app/Http/Controllers/UserWordController.php, app/Http/Controllers/WordController.php, routes/web.php
* `コントローラメソッド`の読みやすさのためにコメントを追加
* `Controller`のコードにコメントを作成
* ネーミングのないルートのネーミングを追加
* コメントに修正する部分があるか
* なし
#
---
=> Refactor controller comment

resources/views/components/card.blade.php
* `Cardコンポーネント`の内部内容がoverflowするとスクロールできるように実装。
* `Cardコンポーネント`のcssを変更
* なし
* なし
* なし
#
---
=> 💄 style: Fix overflow issue in card component

resources/views/layouts/navigation.blade.php
* コミュニティページでナビゲーションバーが正常に表示されないエラーの解決
* ナビゲーションバーのcssを修正
* なし
* なし
* なし
#
---
=> 🐛 fix: Fix navigation layout bug

resources/views/components/profile-card.blade.php
* テスト用に作成しておいた不要なロジックを削除
* 不要な`console.log`の削除
* なし
* なし
* なし
#
---
=> ♻️ refactor: Refactor profile-card.blade.php file

resources/views/components/card.blade.php, resources/views/dashboard.blade.php
* カードコンポーネントでタグ名を追加して、どんな種類の単語か認識できるようにするため
* カードコンポーネントにタグを追加
* なし
* なし
* なし
#
---
=> 💄 style: Add tag card.blade.php and dashboard.blade.php

app/Http/Controllers/UserWordController.php, app/Http/Controllers/WordController.php, app/Models/Tag.php, app/Models/Word.php
* `UserWord`情報を返すとき、タグ情報も一緒に返すため
* `UserWordController`でタグ情報を添付するように修正
* 返品フォームの変更
* なし
* なし
#
---
=> ✨ feat: Refactor UserWordController and WordController with tag

app/Http/Controllers/PostController.php
* 順番にcommentを出力するため
* 昇順条件を追加
* なし
* なし
* なし
#
---
=> ♻️ refactor: Refactor comment retrieval in PostController

app/Http/Controllers/UserTagController.php
* タグ変換ロジックを改善
* タグ名に応じた変換ロジックを追加
* なし
* なし
* なし
#
---
=> ♻️ refactor: Refactor UserTagController to update user tags with transaction

resources/views/profile/partials/favorite-word-form.blade.php, resources/views/profile/partials/unfamiliar-word-form.blade.php
* マイページの`お気に入り`、`知らない`単語の管理ロジックバグを修正
* 単語を出力し、状態を管理するロジックを改善
* なし
* なし
* なし
#
---
=> 🐛 fix: Fix bug word control logic in mypage

app/Models/Post.php
* Post モデルメソッド名修正
* メソッド名をcommentsからcommentに修正
* なし
* なし
* なし
#
---
=> ♻️ refactor: Fix typo in Post model's comment method
